In [1]:
class Animal:
    isalive = True
    age = 0

In [2]:
my_cat = Animal()

In [3]:
print(my_cat)
print(type(my_cat))

<class '__main__.Animal'>


In [4]:
my_cat.isalive

True

In [5]:
my_second_cat = Animal()

In [6]:
my_cat.age == my_second_cat.age

True

In [7]:
my_cat.age = 2

In [8]:
my_cat.age == my_second_cat.age

False

In [9]:
Animal.isalive = False

In [10]:
print(my_cat.isalive)
print(my_second_cat.isalive)

False
False


In [11]:
Animal.isalive = True

In [12]:
class Cat:
    isalive = True
    age = 0
    sound = "meow"

    def __init__(self, location):
        self.location = location.values()

    def aged(self):
        self.age += 1

- packing and unpacking

In [13]:
fruits = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]

In [14]:
first, second, *remaning, last = fruits

In [15]:
print(first)
print(last)
print(second)

apple
mango
banana


In [16]:
print(remaning)

['cherry', 'orange', 'kiwi', 'melon']


In [17]:
def my_example(*args):
    return print(args)

In [18]:
my_example(1, 2, 3, 'a', 'b', 'c')

(1, 2, 3, 'a', 'b', 'c')


In [19]:
def my_example(my_number, *args):
    return f"My number is: {my_number}, {args}"

In [20]:
my_example(10, 11, 12)

'My number is: 10, (11, 12)'

In [21]:
def second_example(**kwargs):
    return kwargs

In [22]:
second_example(number_first_number=10, number_second_number=11,)

{'number_first_number': 10, 'number_second_number': 11}

In [23]:
def third_example(special_number=1, **kwargs):
    return f"Special number: {special_number}, Others: {kwargs}"

In [24]:
third_example(special_number=2, number_first_number=10, number_second_number=11,)

"Special number: 2, Others: {'number_first_number': 10, 'number_second_number': 11}"

In [25]:
# def my_function(<positional_args>, *args, <key-word_args>, **kwargs)

## Numpy

In [26]:
number = 15

In [27]:
type(number)

int

In [28]:
dir(number)

['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'as_integer_ratio',
 'bit_count',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'is_integer',
 

In [29]:
my_list = [1, 2, 3]

In [30]:
dir(my_list)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [31]:
# pip install numpy
# pip3 install numpy

In [32]:
import numpy as np

In [33]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [34]:
array_a = np.array([1, 2, 3, 4])

In [35]:
array_a

array([1, 2, 3, 4])

In [36]:
array_b = np.array([0, .5, 1, 1.5, 2])

In [37]:
array_b

array([0. , 0.5, 1. , 1.5, 2. ])

In [38]:
array_a[0]

np.int64(1)

In [39]:
array_b[-1]

np.float64(2.0)

In [40]:
array_a[:2]

array([1, 2])

In [41]:
array_a.dtype

dtype('int64')

In [42]:
array_b.dtype

dtype('float64')

In [43]:
empty_array = np.array([])

In [44]:
empty_array.dtype

dtype('float64')

In [45]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [46]:
np.array(['veri', 'bilimi'])

array(['veri', 'bilimi'], dtype='<U6')

In [47]:
my_array = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [48]:

array_a.shape

(4,)

In [49]:
my_array.shape

(2, 3)

In [50]:
array_a.ndim

1

In [51]:
my_array.ndim

2

In [52]:
my_array.size

6

In [53]:
my_array = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 6],
        [3, 2, 1]
    ]
])

In [54]:
my_array.ndim

3

In [55]:
my_array.shape

(2, 2, 3)

In [56]:
my_array = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]    
])

In [57]:
my_array[1]

array([4, 5, 6])

In [58]:
my_array[1][0]

np.int64(4)

In [59]:
my_array[1, 0]

np.int64(4)

In [60]:
my_array[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
my_array[:2, :2]

array([[1, 2],
       [4, 5]])

In [62]:
my_array[1] = np.array([10, 10, 10])

In [63]:
my_array

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [64]:
my_array[2] = 99

In [65]:
my_array

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

In [66]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [67]:
my_array = np.arange(0,10)
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
my_array.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [69]:
np.arange(1, 10.1, 4)

array([1., 5., 9.])

In [70]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [71]:
np.ones((2, 5, 3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [72]:
my_array = np.random.random((5,2))

In [73]:
my_array

array([[0.07928045, 0.19816448],
       [0.43874801, 0.32199063],
       [0.1588439 , 0.87057179],
       [0.59604072, 0.31396805],
       [0.13877579, 0.12097032]])

In [74]:
np.linspace(5, 10, 5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [75]:
# any(), all(), full(), concatenate()

In [76]:
array1 = np.arange(0, 10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
array1 = array1.reshape(2, 5)

In [78]:
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [79]:
np.concatenate([array1, array1])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [80]:
array1.sum()

np.int64(45)

In [81]:
array1.mean()

np.float64(4.5)

In [82]:
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [83]:
array1.sum(axis=1)

array([10, 35])

In [84]:
array1.sum(axis=0)

array([ 5,  7,  9, 11, 13])

In [85]:
array1 + 10

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [86]:
array1 += 10
array1

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

- boolean arrays

In [87]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [88]:
a[0], a[-1]

(np.int64(0), np.int64(3))

In [89]:
a[[0, -1]]

array([0, 3])

In [90]:
a[[True, False, False, True]]

array([0, 3])

In [91]:
a >= 2 

array([False, False,  True,  True])

In [92]:
a[a >= 2]

array([2, 3])

In [93]:
a[a > a.mean()]

array([2, 3])

In [94]:
a[(a == 0) | (a == 1)] # instead of and, or, not we will use &|~

array([0, 1])

In [95]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

- 100'e kadar rastgele tamsayılardan oluşan, 3,3 bir matris oluşturun.
- 30'dan büyük olanları boolean yöntemi ile filtreleyin.

In [96]:
rand_array = np.random.randint(100, size=(3,3))

In [97]:
rand_array

array([[ 9,  4, 30],
       [25, 99, 57],
       [16, 32, 16]], dtype=int32)

In [98]:
boolean_array = rand_array > 30

In [99]:
boolean_array

array([[False, False, False],
       [False,  True,  True],
       [False,  True, False]])

In [100]:
rand_array[boolean_array]

array([99, 57, 32], dtype=int32)

In [101]:
rand_array[rand_array > 30]

array([99, 57, 32], dtype=int32)

In [102]:
import sys

In [103]:
sys.getsizeof(10)

28

In [104]:
sys.getsizeof(1000**100)

160

In [105]:
np.dtype(int).itemsize

8

In [106]:
np.dtype(np.int8).itemsize

1

In [107]:
my_list = list(range(1000000))

In [108]:
my_array = np.arange(1000000)

In [109]:
%time np.sum(my_array ** 2)

CPU times: total: 15.6 ms
Wall time: 7.99 ms


np.int64(333332833333500000)

In [110]:
%time sum([number ** 2 for number in my_list])

CPU times: total: 141 ms
Wall time: 136 ms


333332833333500000